development: &development

  #Application
  domain:              "http://localhost:3000"
  facebook_app_id:     "123123"
  facebook_app_secret: "123abc"

test:
  <<: *development

production:

  #Application
  domain:              "http://encuentramipost.herokuapp.com"
  facebook_app_id:     "123123"
  facebook_app_secret: "123abc"
